views:
  - name: executive_dashboard
    title: Executive Dashboard
    description: C-level KPIs and metrics for executive decision making
    
    cubes:
      - join_path: sales_invoices
        includes:
          - total_revenue
          - total_revenue_incl_vat
          - total_outstanding
          - count
          - overdue_amount
          - days_sales_outstanding
          - unique_customers
          
      - join_path: sales_invoice_lines
        prefix: true
        includes:
          - gross_profit
          - gross_margin_percent
          
      - join_path: customers
        includes:
          - count
          - active_count
          - total_credit_limit
          
      - join_path: sales_headers
        prefix: true
        includes:
          - open_orders_value
          - open_orders_count
          - quote_count
          
      - join_path: purchase_invoices
        prefix: true
        includes:
          - total_purchases
          - total_outstanding
          - days_payable_outstanding
          
      - join_path: items
        prefix: true
        includes:
          - total_inventory_value
          - items_out_of_stock
          - items_below_reorder
          
      - join_path: g_l_entries
        prefix: true
        includes:
          - revenue_entries
          - expense_entries
          
      - join_path: vendors
        prefix: true
        includes:
          - count
          - active_vendors
          
  - name: revenue_analytics
    title: Revenue Analytics
    description: Detailed revenue analysis for C-level executives
    
    cubes:
      - join_path: sales_invoices
        includes: "*"
        
      - join_path: customers
        prefix: true
        includes:
          - name
          - country_region_code
          - customer_posting_group
          - salesperson_code
          
      - join_path: sales_invoice_lines
        includes:
          - total_quantity_sold
          - gross_profit
          - gross_margin_percent
          - avg_unit_price
          - avg_discount_given
          
  - name: cash_flow_view
    title: Cash Flow Management
    description: Cash flow and working capital metrics
    
    cubes:
      - join_path: sales_invoices
        includes:
          - total_revenue
          - total_outstanding
          - overdue_amount
          - days_sales_outstanding
          - paid_invoices
          - unpaid_invoices
          - overdue_invoices
          
      - join_path: purchase_invoices
        includes:
          - total_purchases
          - total_outstanding
          - days_payable_outstanding
          - paid_invoices
          - unpaid_invoices
          
      - join_path: g_l_entries
        includes:
          - total_debit
          - total_credit
          - balance
          
  - name: profitability_analysis
    title: Profitability Analysis
    description: Gross margin and profitability metrics by product and customer
    
    cubes:
      - join_path: sales_invoice_lines
        includes:
          - total_revenue
          - total_cost
          - gross_profit
          - gross_margin_percent
          - total_quantity_sold
          
      - join_path: items
        prefix: true
        includes:
          - no
          - description
          - item_category_code
          - type
          
      - join_path: customers
        prefix: true
        includes:
          - name
          - country_region_code
          - customer_posting_group
          
  - name: inventory_management
    title: Inventory Management
    description: Inventory levels, turnover, and optimization metrics
    
    cubes:
      - join_path: items
        includes:
          - count
          - total_inventory_value
          - total_inventory_qty
          - items_below_reorder
          - items_out_of_stock
          - inventory_turns
          
      - join_path: item_ledger_entries
        includes:
          - quantity_in
          - quantity_out
          - total_cost
          - total_sales
          
      - join_path: item_categories
        prefix: true
        includes:
          - code
          - description
          
  - name: customer_analytics
    title: Customer Analytics
    description: Customer segmentation and lifetime value analysis
    
    cubes:
      - join_path: customers
        includes: "*"
        
      - join_path: sales_invoices
        prefix: true
        includes:
          - count
          - total_revenue
          - total_outstanding
          - avg_invoice_value
          
      - join_path: sales_headers
        prefix: true
        includes:
          - order_count
          - open_orders_value
          
  - name: vendor_performance
    title: Vendor Performance
    description: Vendor analysis and procurement metrics
    
    cubes:
      - join_path: vendors
        includes: "*"
        
      - join_path: purchase_invoices
        prefix: true
        includes:
          - count
          - total_purchases
          - total_outstanding
          
      - join_path: purchase_headers
        prefix: true
        includes:
          - order_count
          - open_orders_value
          
  - name: financial_statements
    title: Financial Statements
    description: P&L and Balance Sheet components
    
    cubes:
      - join_path: g_l_entries
        includes:
          - revenue_entries
          - expense_entries
          - asset_entries
          - liability_entries
          - total_debit
          - total_credit
          - balance
          
      - join_path: g_l_accounts
        prefix: true
        includes:
          - no
          - name
          - account_type
          - income_balance
          - account_category
          - account_subcategory_descript