views:
  - name: chart_of_accounts_view
    title: Chart of Accounts Analysis
    description: Comprehensive view for account structure and posting integrity queries with balance calculations and budget comparisons
    public: true
    
    cubes:
      # Include GL Account as the primary cube
      - join_path: g_l_account
        includes:
          # Account identifiers
          - no
          - name
          - search_name
          
          # Account categorization
          - account_category
          - account_subcategory_descript
          - account_type
          - income_balance
          
          # Posting controls
          - direct_posting
          - blocked
          - reconciliation_account
          
          # Account groups
          - gen_posting_type
          - gen_bus_posting_group
          - gen_prod_posting_group
          - vat_bus_posting_group
          - vat_prod_posting_group
          
          # Totaling
          - totaling
          
          # Consolidation
          - consol_translation_method
          - consol_debit_acc
          - consol_credit_acc
          
          # Cost accounting
          - cost_type_no
          
          # Exchange rates
          - exchange_rate_adjustment
          
          # Timestamps
          - last_modified_date_time
          - last_date_modified
          
          # Measures from g_l_account
          - count
          - balance
          - net_change
          - debit_amount
          - credit_amount
          - budgeted_amount
          
          # Segments from g_l_account
          - balance_sheet_accounts
          - income_statement_accounts
          - asset_accounts
          - liability_accounts
          - equity_accounts
          - revenue_accounts
          - expense_accounts
          - cogs_accounts
          - has_general_posting_group
          - has_vat_posting_group
          - active_accounts
          - blocked_accounts
          - direct_posting_allowed
          - no_direct_posting
          - is_reconciliation_account
          - requires_exchange_adjustment
          
      # Include GL Entry data with prefix
      - join_path: g_l_account.g_l_entry
        prefix: true
        includes:
          - posting_date
          - document_type
          - document_no
          - description
          - source_type
          - source_no
          - job_no
          - quantity
          
          # Financial amounts
          - amount
          - debit_amount
          - credit_amount
          - vat_amount
          - additional_currency_amount
          
          # Dimension codes
          - global_dimension_1_code
          - global_dimension_2_code
          - business_unit_code
          
          # User and reason codes
          - user_id
          - reason_code
          
          # Reversal info
          - reversed
          
          # Timestamps
          - last_modified_date_time
          
          # Measures from g_l_entries
          - count
          - total_amount
          - total_debit_amount
          - total_credit_amount
          - avg_amount
          - max_amount
          - min_amount
          - unique_documents
          - unique_sources
          - unique_jobs
          
          # Period-based measures
          - current_period_amount
          - prior_period_amount
          - current_year_amount
          - prior_year_amount
          - period_over_period_change
          - year_over_year_change
          
          
      # Include Company information
      - join_path: g_l_account.company
        prefix: true
        includes:
          - name
          - display_name
          - evaluation_company
    
