views:
  - name: chart_of_accounts_view
    title: Chart of Accounts Analysis
    description: Comprehensive view for account structure, balances, and posting integrity analysis
    public: true
    
    cubes:
      # Include G/L Account master data
      - join_path: g_l_account_extended
        prefix: false
        includes:
          # Primary fields
          - name: no
            alias: account_no
            title: Account Number
            description: General Ledger account number
          
          - name: name
            alias: account_name
            title: Account Name
            
          - name: account_type
            title: Account Type
            description: Posting, Total, Begin-Total, or End-Total
            
          - name: income_balance
            title: Income/Balance Sheet
            description: Income Statement or Balance Sheet account
            
          - name: account_category
            title: Account Category
            description: Detailed account categorization
            
          - name: account_subcategory
            title: Account Subcategory
            
          - name: direct_posting
            title: Direct Posting Allowed
            description: Whether direct posting is allowed to this account
            
          - name: blocked
            title: Account Blocked
            description: Account blocking status
            
          # Financial fields
          - name: balance
            alias: current_balance
            title: Current Balance
            description: Current account balance
            
          - name: net_change
            alias: period_net_change
            title: Period Net Change
            description: Net change in current period
            
          - name: debit_amount
            title: Total Debit Amount
            
          - name: credit_amount
            title: Total Credit Amount
            
          - name: budgeted_amount
            title: Budgeted Amount
            description: Budget allocation for this account
            
          # Extended measures
          - name: budget_variance_amount
            title: Budget Variance Amount
            
          - name: budget_variance_percent
            title: Budget Variance %
            
          - name: budget_utilization
            title: Budget Utilization %
            
          - name: account_turnover
            title: Account Turnover
            
          - name: average_entry_amount
            title: Average Entry Amount
            
          # Posting groups
          - name: gen_posting_type
            title: General Posting Type
            
          - name: gen_bus_posting_group
            title: General Business Posting Group
            
          - name: gen_prod_posting_group
            title: General Product Posting Group
            
          - name: vat_bus_posting_group
            title: VAT Business Posting Group
            
          - name: vat_prod_posting_group
            title: VAT Product Posting Group
            
          # Consolidation fields
          - name: consol_debit_acc
            title: Consolidation Debit Account
            
          - name: consol_credit_acc
            title: Consolidation Credit Account
            
          # Audit fields
          - name: system_created_at
            title: Created Date
            
          - name: system_modified_at
            title: Modified Date
      
      # Include G/L Entry transactional data
      - join_path: g_l_account_extended.g_l_entry
        prefix: true
        includes:
          - name: system_id
            title: Entry ID
            
          - name: posting_date
            title: Posting Date
            
          - name: document_type
            title: Document Type
            
          - name: document_no
            title: Document Number
            
          - name: description
            title: Entry Description
            
          - name: amount
            title: Entry Amount
            
          - name: debit_amount
            title: Entry Debit Amount
            
          - name: credit_amount
            title: Entry Credit Amount
            
          - name: vat_amount
            title: VAT Amount
            
          - name: source_type
            title: Source Type
            
          - name: source_no
            title: Source Number
            
          - name: user_id
            title: User ID
            
          # Dimensions
          - name: global_dimension_1_code
            title: Global Dimension 1
            
          - name: global_dimension_2_code
            title: Global Dimension 2
            
          - name: dimension_set_id
            title: Dimension Set ID
            
          # Measures from g_l_entry
          - name: count
            alias: entry_count
            title: Number of Entries
            
          - name: dimension_changes_count
            title: Dimension Changes Count
      
      # Include Company information
      - join_path: g_l_account_extended.company
        prefix: true
        includes:
          - name: name
            title: Company Name
            
          - name: display_name
            title: Company Display Name
            
          - name: id
            title: Company ID