/**
 * Executive Dashboard View - Main C-Suite Dashboard
 * 
 * Comprehensive executive dashboard combining key financial KPIs, customer metrics,
 * operational metrics, revenue and growth indicators, risk indicators, and strategic
 * initiatives tracking for C-level executives.
 * 
 * Provides:
 * - Key financial KPIs (revenue, expenses, profitability)
 * - Customer metrics (acquisition, retention, lifetime value)
 * - Operational metrics (efficiency, productivity, utilization)
 * - Revenue and growth indicators (trends, forecasts)
 * - Risk indicators (exposure, concentration, compliance)
 * - Strategic initiatives tracking (goals, milestones, performance)
 * 
 * Target Audience: CEO, CFO, COO, CRO, and Board Members
 */

view('executive_dashboard', {
  description: 'Comprehensive C-suite executive dashboard with key financial KPIs, customer metrics, operational performance, and strategic indicators',
  
  includes: [
    // ===== FINANCIAL CORE METRICS =====
    g_l_entry.total_amount,
    g_l_entry.total_debit_amount, 
    g_l_entry.total_credit_amount,
    g_l_entry.total_vat_amount,
    g_l_entry.net_amount,
    g_l_entry.average_transaction_amount,
    g_l_entry.debit_transaction_count,
    g_l_entry.credit_transaction_count,
    g_l_entry.reversed_entries_count,
    g_l_entry.running_balance,
    g_l_entry.count,
    g_l_entry.posting_date,
    g_l_entry.document_date,
    g_l_entry.document_type,
    g_l_entry.document_no,
    g_l_entry.g_laccount_no,
    g_l_entry.g_laccount_name,
    g_l_entry.description,
    g_l_entry.source_type,
    g_l_entry.source_code,
    g_l_entry.global_dimension_1_code,
    g_l_entry.global_dimension_2_code,
    g_l_entry.business_unit_code,
    g_l_entry.gen_bus_posting_group,
    g_l_entry.gen_prod_posting_group,
    g_l_entry.vat_bus_posting_group,
    g_l_entry.vat_prod_posting_group,
    g_l_entry.company_id,
    
    // ===== CHART OF ACCOUNTS STRUCTURE =====
    g_l_account.total_balance,
    g_l_account.total_debit_amount,
    g_l_account.total_credit_amount,
    g_l_account.average_balance,
    g_l_account.posting_accounts_count,
    g_l_account.heading_accounts_count,
    g_l_account.total_accounts_count,
    g_l_account.begin_total_accounts_count,
    g_l_account.end_total_accounts_count,
    g_l_account.blocked_accounts_count,
    g_l_account.direct_posting_accounts_count,
    g_l_account.reconciliation_accounts_count,
    g_l_account.income_statement_accounts_count,
    g_l_account.balance_sheet_accounts_count,
    g_l_account.tax_liable_accounts_count,
    g_l_account.count,
    g_l_account.no,
    g_l_account.name,
    g_l_account.account_type,
    g_l_account.income_balance,
    g_l_account.account_category,
    g_l_account.account_subcategory_descript,
    g_l_account.blocked,
    g_l_account.direct_posting,
    g_l_account.reconciliation_account,
    g_l_account.tax_liable,
    g_l_account.gen_bus_posting_group,
    g_l_account.gen_prod_posting_group,
    g_l_account.vat_bus_posting_group,
    g_l_account.vat_prod_posting_group,
    g_l_account.gen_posting_type,
    g_l_account.company_id,
    
    // ===== CUSTOMER PERFORMANCE METRICS =====
    customer.total_customer_balance,
    customer.average_customer_balance,
    customer.active_customers_count,
    customer.blocked_customers_count,
    customer.customers_with_balance_count,
    customer.customers_with_credit_balance_count,
    customer.tax_liable_customers_count,
    customer.privacy_blocked_customers_count,
    customer.max_customer_balance,
    customer.min_customer_balance,
    customer.customers_by_currency,
    customer.customers_by_payment_terms,
    customer.customers_by_price_group,
    customer.customers_with_email_count,
    customer.customers_with_mobile_count,
    customer.count,
    customer.no,
    customer.name,
    customer.city,
    customer.country_region_code,
    customer.blocked,
    customer.privacy_blocked,
    customer.tax_liable,
    customer.prices_including_vat,
    customer.customer_posting_group,
    customer.gen_bus_posting_group,
    customer.vat_registration_no,
    customer.payment_terms_code,
    customer.payment_method_code,
    customer.currency_code,
    customer.customer_price_group,
    customer.salesperson_code,
    customer.shipping_agent_code,
    customer.language_code,
    customer.company_id,
    
    // ===== CASH POSITION AND LIQUIDITY =====
    bank_account.count,
    bank_account.no,
    bank_account.name,
    bank_account.balance,
    bank_account.balance_lcy,
    bank_account.balance_last_statement,
    bank_account.net_change,
    bank_account.net_change_lcy,
    bank_account.min_balance,
    bank_account.currency_code,
    bank_account.bank_code,
    bank_account.bank_branch_no,
    bank_account.bank_account_no,
    bank_account.iban,
    bank_account.swift_code,
    bank_account.blocked,
    bank_account.bank_acc_posting_group,
    bank_account.country_region_code,
    bank_account.automatic_stmt_import_enabled,
    bank_account.company_id,
    
    // ===== ORGANIZATIONAL STRUCTURE =====
    employee.count,
    employee.no,
    employee.first_name,
    employee.last_name,
    employee.job_title,
    employee.employment_date,
    employee.termination_date,
    employee.status,
    employee.inactive_date,
    employee.manager_no,
    employee.resource_no,
    employee.salespers_purch_code,
    employee.employee_posting_group,
    employee.emplymt_contract_code,
    employee.statistics_group_code,
    employee.global_dimension_1_code,
    employee.global_dimension_2_code,
    employee.cost_center_code,
    employee.cost_object_code,
    employee.country_region_code,
    employee.company_email,
    employee.privacy_blocked,
    employee.company_id,
    
    // ===== COMPANY INFORMATION =====
    company.count,
    company.id,
    company.display_name,
    company.business_profile_id,
    company.system_version,
    company.evaluation_company
  ]
});