-- Create warehouse for Cube
CREATE WAREHOUSE IF NOT EXISTS cube_warehouse
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Create role and user for Cube.js
CREATE ROLE IF NOT EXISTS CUBE_ROLE;
CREATE USER IF NOT EXISTS cube_service;

-- Assign public key to user (replace with your public key)
ALTER USER cube_service SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3RiWRZwfRAK3xSzcQlBF
EwlonGna9BgNMTnl+8CpuaSEiklUmWkNtGQdI435G8J8RHqrNuHt+aXY+AIQGdKZ
ptjFzIuIdaPIp/PNRSaYerSGxGjL4GPea8ADsaPPrWhu9wIDICneEAPQlYaURWC3
io7JccQBArws0y1gTPY/dk7pIK7n7CWOqG1PSQkIUej/9RejfGctbT0jej0X7X7b
p3Gg/LCv1GJD4nGBRVz6lesdG5BwuIWMmcj+cpN/Sh6qgqjj2Ey4kh/+IWGgryYt
WlPH0UOCo/8Hw3MzHi6EB5H8OGSffrAiXB1CnyRWqp13QfG8Mv0c1oqSzhZ+8UaD
0QIDAQAB
-----END PUBLIC KEY-----'; 

-- Grant necessary permissions
GRANT ROLE CUBE_ROLE TO USER cube_service;
GRANT USAGE ON WAREHOUSE cube_warehouse TO ROLE CUBE_ROLE;
GRANT USAGE ON DATABASE FIVETRAN_DATABASE TO ROLE CUBE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FIVETRAN_DATABASE TO ROLE CUBE_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FIVETRAN_DATABASE TO ROLE CUBE_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FIVETRAN_DATABASE TO ROLE CUBE_ROLE;

-- Set default role and warehouse
ALTER USER cube_service SET DEFAULT_ROLE = CUBE_ROLE;
ALTER USER cube_service SET DEFAULT_WAREHOUSE = cube_warehouse;

-- Verify configuration
DESC USER cube_service;